@csrf
@if($patient->exists) @method('PUT') @endif

<div class="space-y-6">
    @unless($patient->exists)
        <x-form-section title="Account Setup" description="Create an optional patient login account. Patient number and QR token are generated by the server.">
            <label class="flex items-center gap-2 md:col-span-2">
                <input type="checkbox" name="create_account" value="1" @checked(old('create_account')) class="rounded border-gray-300">
                <span class="text-sm font-medium text-gray-700">Create login account</span>
            </label>
            <div>
                <x-input-label for="temporary_password" value="Temporary Password" />
                <x-text-input id="temporary_password" name="temporary_password" type="password" class="mt-1 block w-full" />
                <x-input-error class="mt-2" :messages="$errors->get('temporary_password')" />
            </div>
            <div>
                <x-input-label for="temporary_password_confirmation" value="Confirm Password" />
                <x-text-input id="temporary_password_confirmation" name="temporary_password_confirmation" type="password" class="mt-1 block w-full" />
            </div>
        </x-form-section>
    @endunless

    <x-form-section title="Personal Information">
        @foreach(['first_name' => 'First Name', 'middle_name' => 'Middle Name', 'last_name' => 'Last Name', 'suffix' => 'Suffix'] as $field => $label)
            <div>
                <x-input-label :for="$field" :value="$label" />
                <x-text-input :id="$field" :name="$field" class="mt-1 block w-full" :value="old($field, $patient->{$field})" :required="in_array($field, ['first_name', 'last_name'])" />
                <x-input-error class="mt-2" :messages="$errors->get($field)" />
            </div>
        @endforeach
        <div>
            <x-input-label for="date_of_birth" value="Date of Birth" />
            <x-text-input id="date_of_birth" name="date_of_birth" type="date" class="mt-1 block w-full" :value="old('date_of_birth', $patient->date_of_birth?->format('Y-m-d'))" required />
            <x-input-error class="mt-2" :messages="$errors->get('date_of_birth')" />
        </div>
        <div>
            <x-input-label for="sex" value="Sex" />
            <select id="sex" name="sex" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm">
                @foreach($sexes as $sex)
                    <option value="{{ $sex->value }}" @selected(old('sex', $patient->sex?->value) === $sex->value)>{{ $sex->label() }}</option>
                @endforeach
            </select>
        </div>
        <div>
            <x-input-label for="civil_status" value="Civil Status" />
            <x-text-input id="civil_status" name="civil_status" class="mt-1 block w-full" :value="old('civil_status', $patient->civil_status)" />
        </div>
        <div>
            <x-input-label for="blood_type" value="Blood Type" />
            <select id="blood_type" name="blood_type" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm">
                <option value="">Not verified</option>
                @foreach($bloodTypes as $bloodType)
                    <option value="{{ $bloodType }}" @selected(old('blood_type', $patient->blood_type) === $bloodType)>{{ $bloodType }}</option>
                @endforeach
            </select>
        </div>
        <div class="md:col-span-2">
            <x-input-label for="profile_photo" value="Profile Photo" />
            <input id="profile_photo" name="profile_photo" type="file" accept="image/jpeg,image/png,image/webp" class="mt-1 block w-full text-sm">
            <x-input-error class="mt-2" :messages="$errors->get('profile_photo')" />
        </div>
    </x-form-section>

    <x-form-section title="Contact and Insurance">
        <div>
            <x-input-label for="email" value="Email" />
            <x-text-input id="email" name="email" type="email" class="mt-1 block w-full" :value="old('email', $patient->email)" />
            <x-input-error class="mt-2" :messages="$errors->get('email')" />
        </div>
        <div>
            <x-input-label for="contact_number" value="Contact Number" />
            <x-text-input id="contact_number" name="contact_number" class="mt-1 block w-full" :value="old('contact_number', $patient->contact_number)" />
            <x-input-error class="mt-2" :messages="$errors->get('contact_number')" />
        </div>
        @foreach(['address_line_1' => 'Address Line 1', 'address_line_2' => 'Address Line 2', 'barangay' => 'Barangay', 'city_municipality' => 'City/Municipality', 'province' => 'Province', 'postal_code' => 'Postal Code', 'insurance_provider' => 'Insurance Provider', 'insurance_number' => 'Insurance Number'] as $field => $label)
            <div>
                <x-input-label :for="$field" :value="$label" />
                <x-text-input :id="$field" :name="$field" class="mt-1 block w-full" :value="old($field, $patient->{$field})" />
            </div>
        @endforeach
        <div>
            <x-input-label for="registration_date" value="Registration Date" />
            <x-text-input id="registration_date" name="registration_date" type="date" class="mt-1 block w-full" :value="old('registration_date', $patient->registration_date?->format('Y-m-d') ?? now()->format('Y-m-d'))" />
        </div>
        <div>
            <x-input-label for="status" value="Status" />
            <select id="status" name="status" class="mt-1 block w-full rounded-md border-gray-300 shadow-sm">
                @foreach($statuses as $status)
                    <option value="{{ $status->value }}" @selected(old('status', $patient->status?->value ?? 'active') === $status->value)>{{ $status->label() }}</option>
                @endforeach
            </select>
        </div>
    </x-form-section>

    @if(session('possible_duplicates'))
        <div class="rounded-md border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">
            Possible duplicate patients were found. Review before continuing.
            <input type="hidden" name="duplicate_override" value="1">
        </div>
    @endif

    <div class="flex justify-end gap-3">
        <a href="{{ route('admin.patients.index') }}" class="rounded-md border border-gray-300 px-4 py-2 text-sm font-medium text-gray-700">Cancel</a>
        <button class="rounded-md bg-gray-950 px-4 py-2 text-sm font-semibold text-white">Save Patient</button>
    </div>
</div>
